name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configurar Docker Buildx (mejor compatibilidad)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Loguear en Docker (opcional si subes la imagen a Docker Hub)
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t oscar .

    # 5. (Opcional) Ejecutar la imagen para probar que funciona
    - name: Test Docker image
      run: docker run --rm oscar




