name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --progress=plain -t oscar .

      - name: Run sandbox and tests
        run: |
          # Ejecutar contenedor temporal para correr tests
          docker run --rm oscar make test


